### ISSUE TITLE
create new document from folder is added to folder list

### ISSUE THREAD

**Issue by meiranhadad** [linnovate/root#1665] opened 2019-03-25 14:05 UTC
go to Settings -> Folders
create new folder 
go to Documents -> manage documents
create new document (from folder)
![image](https://user-images.githubusercontent.com/45143091/54925713-84101780-4f17-11e9-8d0c-f841789cef39.png)
go to Settings -> Folders
the new document appear at the list of all the folders
![image](https://user-images.githubusercontent.com/45143091/54925794-b3268900-4f17-11e9-86d3-256a6bfb869c.png)

**Comment by AvrahamO** [comment] 2019-04-10 15:13
I couldn't reproduce this bug

**Comment by meiranhadad** [comment] 2019-04-14 08:42
remark: only happens if you create a folder and immediately after it creates a document.

**Comment by AvrahamO** [comment] 2019-04-14 11:21
Fixed by 129ae13ac776dcff5736d558873619a4dd7e42a2

**Closed** 2019-04-18 12:17 UTC
Labels: 2.0.6.1, Fixed, Settings
