### ISSUE TITLE
delete tags that related to deleted folder

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1322] opened 2018-11-12 13:17 UTC
press on settings
crate a new folder and call it 101 
press on documents
crate a new item and call it TEST_101 
press on "choose folder" and select 101 folder
(the document is connected to 101 folder )
 press on settings again 
delete the the 101 folder 
it shows that the document still connected to deleted folder (101)

**Comment by manmorc** [comment] 2018-11-15 12:19
Hello @YehudaMorad , thank you for Hebrew message!

**Comment by YehudaMorad** [comment] 2018-11-18 13:06
Hi @manmorc I hope it's OK now.

**Comment by abrahamos** [comment] 2018-11-27 11:05
We need an exact expectation for such a case.
This is not a bug, but some undefined case which was not designed.

**Comment by chensabag** [comment] 2018-12-12 10:18
This case also repeats itself in the connection between tasks and projects.

**Comment by chensabag** [comment] 2018-12-18 14:37
@abrahamos 
show at prd 206 section 6

**Comment by chensabag** [comment] 2018-12-25 11:20
When you delete entities - all their relationships will be deleted.
Only the relationships will be erased, not the entities themselves.
For example:
When a project is linked to tasks, and we delete the project, the tasks associated to that project aren't deleted. Only the relationship itself was deleted.

**Comment by abrahamos** [comment] 2018-12-27 16:11
Fixed by 0db861eb900c5b70b210e08368100db026c5ba6e

**Comment by AviramAshkenazi** [comment] 2019-01-01 10:01
fix

**Closed by AviramAshkenazi** 2019-01-01 10:01 UTC
Labels: 2.0.6, Fixed, Process bug
