### ISSUE TITLE
projects visual bug

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#867] opened 2018-05-22 07:25 UTC
in the projects template, the color button is above the status 
![project visual](https://user-images.githubusercontent.com/31100069/40347838-5e6f8d8a-5daa-11e8-8cb0-4e48fe591b1c.png)

**Comment by nevos** [comment] 2018-05-22 08:30
@AviramAshkenazi duplicate of #851

**Closed by nevos** 2018-05-22 08:30 UTC
