### ISSUE TITLE
Permissions: viewer can still change the name of every entity he's viewing

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#721] opened 2018-04-12 08:36 UTC
@AviramAshkenazi @nevos 
a user with the "viewer" permission can still change the name on each entity he's viewing even though it's not saved after refreshing the page, when he shouldn't be able to do anything but view it.

**Comment by nevos** [comment] 2018-04-12 09:36
duplicate of https://github.com/linnovate/root/issues/725

**Closed by nevos** 2018-04-12 09:36 UTC
