### ISSUE TITLE
attachement details view

### ISSUE THREAD

**Issue by liorkesos** [linnovate/root#531] opened 2018-01-07 13:46 UTC
When searching for a direct name in the search show the attachment view in preview mode

**Comment by nevos** [comment] 2018-01-17 14:24
We can possibly use an opensource document viewer like ... #534

**Comment by nevos** [comment] 2018-02-01 12:37
@liorkesos duplicate of #534?

**Comment by nevos** [comment] 2018-02-12 08:21
comment: finetune requirements and design needed.

**Closed** 2018-03-07 08:57 UTC
Labels: week2
