### ISSUE TITLE
color change: critical

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#736] opened 2018-04-12 12:30 UTC
@nevos @AviramAshkenazi  After changing the color in every entity, the server crashes

**Comment by nevos** [comment] 2018-04-12 13:59
seems duplicate of :
https://github.com/linnovate/root/issues/722

**Comment by nevos** [comment] 2018-04-15 14:41
@ohadetsion did you manage to duplicate? any news?

**Comment by nevos** [comment] 2018-04-16 09:45
not reproducible

**Closed by nevos** 2018-04-16 09:45 UTC
Labels: 2.0.3, critical
